# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI build Jar Artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mkdir staging
        javac -sourcepath src -d classes src/Main.java
        jar cvfm sample.jar MANIFEST.MF -C classes staging
        

    - uses: actions/upload-artifact@v1
      with:
        name: ReverseCharacter
        path: staging
